// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwuKxyIAFsJmBrn4bGSCCpXfmvzASOa88',
    appId: '1:668001745302:web:2a44e3c98416c322cac5b7',
    messagingSenderId: '668001745302',
    projectId: 'massaclinic-6b211',
    authDomain: 'massaclinic-6b211.firebaseapp.com',
    storageBucket: 'massaclinic-6b211.firebasestorage.app',
    measurementId: 'G-10EMC59QKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk4oZdTrZ9okG7NT3MmkgxhP0Z_Gg96Jc',
    appId: '1:668001745302:android:66e378d8606aa193cac5b7',
    messagingSenderId: '668001745302',
    projectId: 'massaclinic-6b211',
    storageBucket: 'massaclinic-6b211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD90jwLBNNozHzortTJtYiu2spl4wqOrdk',
    appId: '1:668001745302:ios:c013d5c053451326cac5b7',
    messagingSenderId: '668001745302',
    projectId: 'massaclinic-6b211',
    storageBucket: 'massaclinic-6b211.firebasestorage.app',
    iosBundleId: 'com.example.massaclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD90jwLBNNozHzortTJtYiu2spl4wqOrdk',
    appId: '1:668001745302:ios:c013d5c053451326cac5b7',
    messagingSenderId: '668001745302',
    projectId: 'massaclinic-6b211',
    storageBucket: 'massaclinic-6b211.firebasestorage.app',
    iosBundleId: 'com.example.massaclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwuKxyIAFsJmBrn4bGSCCpXfmvzASOa88',
    appId: '1:668001745302:web:352a9fda9780dddfcac5b7',
    messagingSenderId: '668001745302',
    projectId: 'massaclinic-6b211',
    authDomain: 'massaclinic-6b211.firebaseapp.com',
    storageBucket: 'massaclinic-6b211.firebasestorage.app',
    measurementId: 'G-1XV22ETPT7',
  );
}
